### ISSUE TITLE
Different transition matrices

### ISSUE THREAD

**Issue by DrMikeMaik** [DavideAltomare/ChannelAttribution#12]
The transition matrix that is returned from the `markov_model` with the flag `out_more=True` is different than the transition matrix returned directly from the `transition_matrix` function. 

I checked this using the Data.csv file provided for the examples.

**Comment by DrMikeMaik** [comment]
It has been two weeks since my question. I can provide more details if necessary. Using the sample dataset, `Data.csv` I am running two functions (`markov_model` and `transition_matrix`): 
<img width="501" alt="functions" src="https://github.com/DavideAltomare/ChannelAttribution/assets/30041132/2fedc6b2-b0f6-4157-9048-b5e5c18eacd7">
As you can see they take the exact same data and according to the documentation should calculate the same thing (unless I am mistaken). 
The results however differ between the two functions as can be seen in the two images below.
Markov:
<img width="448" alt="markov_tr_mat" src="https://github.com/DavideAltomare/ChannelAttribution/assets/30041132/a347b06e-673b-4698-b037-1e12e5541ad7">
Transitions:
<img width="404" alt="trasition_tr_mat" src="https://github.com/DavideAltomare/ChannelAttribution/assets/30041132/44d17ea7-0095-47e6-831b-cf003d4300d7">
If my understanding of what these functions should return is wrong please explain the difference.

**Comment by DavideAltomare** [comment]
@DrMikeMaik  : "markov_model" does not consider self-transitions while "transition_matrix" considers self-transitions by default (flg_equal=True) so you need to to set flg_equal=False in function "transition_matrix" if you want the same result in "markov_model".

**Comment by DrMikeMaik** [comment]
Thank you so much for the response. I have check the data and everything now makes sense.
