### ISSUE TITLE
How do I test run the application?

### ISSUE THREAD

**Issue by maoo** [DavideAltomare/ChannelAttribution#2]
Would be great to have some simple data models and some documentation on how to:
1. prepare a dataset
2. execute the application, showing how to pass the dataset as input
3. how to collect and navigate the output

README.md is the best place for this content right now.

**Comment by DavideAltomare** [comment]
fixed

**Comment by maoo** [comment]
Thanks Davide!

Could you please point me to the documentation on how to test run the
application locally?

**Comment by maoo** [comment]
Let's follow up on https://gitlab.com/session-tech/ChannelAttribution/-/issues/3
